from datetime import date as datetime_date
from flask import (
    Flask,
    render_template,
    request,
    redirect,
    session,
    url_for,
    make_response,
    send_from_directory
)
from flask_bcrypt import Bcrypt
from flask_wtf.csrf import CSRFProtect
from dotenv import load_dotenv
from functools import wraps
from psycopg.rows import dict_row
import psycopg
import os
import time
import cloudinary
import cloudinary.uploader
from werkzeug.utils import secure_filename

# =========================================================
# ENVIRONMENT
# =========================================================

load_dotenv()



DATABASE_URL = os.environ.get("DATABASE_URL")

if not DATABASE_URL:
    raise RuntimeError("DATABASE_URL is not set in .env")

# =========================================================
# CLOUDINARY CONFIGURATION
# =========================================================

CLOUDINARY_CLOUD_NAME = os.environ.get("CLOUDINARY_CLOUD_NAME")
CLOUDINARY_API_KEY = os.environ.get("CLOUDINARY_API_KEY")
CLOUDINARY_API_SECRET = os.environ.get("CLOUDINARY_API_SECRET")

if not CLOUDINARY_CLOUD_NAME:
    raise RuntimeError("CLOUDINARY_CLOUD_NAME is not set in .env")

if not CLOUDINARY_API_KEY:
    raise RuntimeError("CLOUDINARY_API_KEY is not set in .env")

if not CLOUDINARY_API_SECRET:
    raise RuntimeError("CLOUDINARY_API_SECRET is not set in .env")

cloudinary.config(
    cloud_name=CLOUDINARY_CLOUD_NAME,
    api_key=CLOUDINARY_API_KEY,
    api_secret=CLOUDINARY_API_SECRET,
    secure=True
)

# =========================================================
# APP SETUP
# =========================================================

BASE_DIR = os.path.dirname(
    os.path.dirname(
        os.path.abspath(__file__)
    )
)

FRONTEND_DIR = os.path.join(
    BASE_DIR,
    "Frontend"
)

app = Flask(
    __name__,
    template_folder=FRONTEND_DIR
)

csrf = CSRFProtect(app)


# =========================================================
# SECRET KEY
# =========================================================

app.secret_key = os.environ.get(
    "SECRET_KEY",
    "dev-change-this-before-production"
)


# =========================================================
# SESSION SECURITY
# =========================================================

app.config["PERMANENT_SESSION_LIFETIME"] = 1800
app.config["SESSION_REFRESH_EACH_REQUEST"] = True

app.config["SESSION_COOKIE_HTTPONLY"] = True
app.config["SESSION_COOKIE_SAMESITE"] = "Lax"

# HTTPS / Render
app.config["SESSION_COOKIE_SECURE"] = True


bcrypt = Bcrypt(app)
app.config["MAX_CONTENT_LENGTH"] = 5 * 1024 * 1024


# =========================================================
# LOGIN SECURITY
# =========================================================

MAX_LOGIN_ATTEMPTS = 5
LOCKOUT_TIME = 300

# =========================================================
# PHOTO UPLOAD SECURITY
# =========================================================

ALLOWED_IMAGE_EXTENSIONS = {
    "jpg",
    "jpeg",
    "png",
    "webp"
}


def allowed_image(filename):

    if not filename or "." not in filename:
        return False

    extension = filename.rsplit(".", 1)[1].lower()

    return extension in ALLOWED_IMAGE_EXTENSIONS

# =========================================================
# DATABASE CONNECTION
# =========================================================

def get_db_connection():

    connection = psycopg.connect(
        DATABASE_URL,
        row_factory=dict_row
    )

    return connection


# =========================================================
# DATABASE INITIALIZATION
# =========================================================

def initialize_database():

    connection = get_db_connection()

    try:

        cursor = connection.cursor()

        # -------------------------------------------------
        # BOOKINGS TABLE
        # -------------------------------------------------

        cursor.execute("""
            CREATE TABLE IF NOT EXISTS bookings (
                id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                name TEXT NOT NULL,
                mobile TEXT NOT NULL,
                car_model TEXT NOT NULL,
                glass_type TEXT NOT NULL,
                date TEXT NOT NULL,
                message TEXT,
                status TEXT DEFAULT 'Pending'
            )
        """)

        # -------------------------------------------------
        # ADMINS TABLE
        # -------------------------------------------------

        cursor.execute("""
            CREATE TABLE IF NOT EXISTS admins (
                id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                username TEXT UNIQUE NOT NULL,
                password TEXT NOT NULL
            )
        """)

        # -------------------------------------------------
        # BOOKING PHOTOS TABLE
        # -------------------------------------------------

        cursor.execute("""
            CREATE TABLE IF NOT EXISTS booking_photos (
                id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                booking_id INTEGER NOT NULL,
                filename TEXT NOT NULL,
                uploaded_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

                CONSTRAINT fk_booking_photos_booking
                FOREIGN KEY (booking_id)
                REFERENCES bookings(id)
                ON DELETE CASCADE
            )
        """)

        connection.commit()

    finally:

        connection.close()


initialize_database()


# =========================================================
# LOGIN REQUIRED
# =========================================================

def login_required(f):

    @wraps(f)
    def decorated_function(*args, **kwargs):

        if (
            "admin_id" not in session
            or
            "username" not in session
        ):

            session.clear()

            return redirect(
                url_for("login")
            )

        return f(*args, **kwargs)

    return decorated_function


# =========================================================
# PWA - MANIFEST
# =========================================================

@app.route("/manifest.json")
def manifest():

    manifest_path = os.path.join(
        FRONTEND_DIR,
        "manifest.json"
    )

    if not os.path.isfile(manifest_path):
        return "Manifest not found.", 404

    with open(
        manifest_path,
        "r",
        encoding="utf-8"
    ) as file:

        content = file.read()

    return content, 200, {
        "Content-Type": "application/manifest+json"
    }


# =========================================================
# PWA - ICONS
# =========================================================

@app.route("/icons/<path:filename>")
def pwa_icons(filename):

    icons_folder = os.path.join(
        FRONTEND_DIR,
        "icons"
    )

    return send_from_directory(
        icons_folder,
        filename
    )


# =========================================================
# HOME
# =========================================================

@app.route("/")
def home():

    return render_template(
        "index.html"
    )

# =========================================================
# CUSTOMER PROFILE
# =========================================================

@app.route("/profile")
def profile():

    # -----------------------------------------------------
    # CUSTOMER MOBILE FROM SESSION
    # -----------------------------------------------------

    customer_mobile = session.get(
        "customer_mobile"
    )

    # -----------------------------------------------------
    # CUSTOMER NOT VERIFIED
    # -----------------------------------------------------

    if not customer_mobile:

        return render_template(
            "profile.html",
            customer=None,
            total_bookings=0,
            completed_services=0
        )

    # -----------------------------------------------------
    # DATABASE CONNECTION
    # -----------------------------------------------------

    connection = get_db_connection()

    try:

        cursor = connection.cursor()

        # -------------------------------------------------
        # CUSTOMER INFORMATION
        # -------------------------------------------------

        cursor.execute(
            """
            SELECT
                name,
                mobile
            FROM bookings
            WHERE mobile = %s
            ORDER BY id DESC
            LIMIT 1
            """,
            (customer_mobile,)
        )

        customer = cursor.fetchone()

        # -------------------------------------------------
        # TOTAL BOOKINGS
        # -------------------------------------------------

        cursor.execute(
            """
            SELECT COUNT(*)
            FROM bookings
            WHERE mobile = %s
            """,
            (customer_mobile,)
        )

        total_bookings = cursor.fetchone()["count"]

        # -------------------------------------------------
        # COMPLETED SERVICES
        # -------------------------------------------------

        cursor.execute(
            """
            SELECT COUNT(*)
            FROM bookings
            WHERE mobile = %s
              AND status = %s
            """,
            (
                customer_mobile,
                "Completed"
            )
        )

        completed_services = cursor.fetchone()["count"]

    finally:

        connection.close()

    # -----------------------------------------------------
    # SHOW PROFILE
    # -----------------------------------------------------

    return render_template(
        "profile.html",
        customer=customer,
        total_bookings=total_bookings,
        completed_services=completed_services
    )

# =========================================================
# BOOK SERVICE
# =========================================================

@app.route("/book", methods=["GET", "POST"])
def book():

    # -----------------------------------------
    # OPEN BOOKING FORM
    # -----------------------------------------
    if request.method == "GET":
        return render_template("index.html")

    name = request.form.get("name", "").strip()
    mobile = request.form.get("mobile", "").strip()
    car_model = request.form.get("car_model", "").strip()
    glass_type = request.form.get("glass_type", "").strip()
    booking_date = request.form.get("date", "").strip()
    message = request.form.get("message", "").strip()

    # -----------------------------------------
    # PHOTO FROM BOOKING FORM
    # -----------------------------------------
    photo = request.files.get("photo")

    # -----------------------------------------
    # BASIC VALIDATION
    # -----------------------------------------
    if not name:
        return "Please enter your name.", 400

    if not mobile:
        return "Please enter your mobile number.", 400

    if not mobile.isdigit():
        return "Please enter numbers only 😊", 400

    if len(mobile) != 10:
        return "Please enter a valid 10-digit mobile number.", 400

    if not car_model:
        return "Please enter car model.", 400

    if not glass_type:
        return "Please select glass type.", 400

    if not booking_date:
        return "Please select service date.", 400

    # -----------------------------------------
    # DATE VALIDATION
    # -----------------------------------------
    try:
        selected_date = datetime_date.fromisoformat(booking_date)
    except ValueError:
        return "Invalid service date.", 400

    if selected_date < datetime_date.today():
        return "Service date cannot be in the past.", 400

    # -----------------------------------------
    # PHOTO VALIDATION
    # -----------------------------------------
    if photo and photo.filename:
        if not allowed_image(photo.filename):
            return (
                "Only JPG, JPEG, PNG and WebP images are allowed.",
                400
            )

    # -----------------------------------------
    # CREATE BOOKING
    # -----------------------------------------
    connection = get_db_connection()

    try:
        cursor = connection.cursor()

        cursor.execute(
            """
            INSERT INTO bookings
            (
                name,
                mobile,
                car_model,
                glass_type,
                date,
                message,
                status
            )
            VALUES (%s, %s, %s, %s, %s, %s, %s)
            RETURNING id
            """,
            (
                name,
                mobile,
                car_model,
                glass_type,
                booking_date,
                message,
                "Pending"
            )
        )

        booking_id = cursor.fetchone()["id"]

        connection.commit()

    finally:
        connection.close()

    # -----------------------------------------
    # PHOTO UPLOAD TO CLOUDINARY
    # -----------------------------------------
    photo_uploaded = False
    photo_error = False

    if photo and photo.filename:
        try:
            upload_result = cloudinary.uploader.upload(
                photo,
                folder="golden_car_glass/bookings"
            )

            secure_url = upload_result.get("secure_url")

            if secure_url:
                connection = get_db_connection()

                try:
                    cursor = connection.cursor()

                    cursor.execute(
                        """
                        INSERT INTO booking_photos
                        (
                            booking_id,
                            filename
                        )
                        VALUES (%s, %s)
                        """,
                        (
                            booking_id,
                            secure_url
                        )
                    )

                    connection.commit()

                    photo_uploaded = True

                finally:
                    connection.close()

        except Exception as e:
            print(
                "CLOUDINARY BOOKING PHOTO UPLOAD ERROR:",
                repr(e)
            )
            photo_error = True

    # -----------------------------------------
    # PHOTO STATUS MESSAGE
    # -----------------------------------------
    if photo_uploaded:
        photo_message = """
        <p style="color:green; font-weight:bold;">
            📸 Your car photo has been uploaded successfully.
        </p>
        """

    elif photo_error:
        photo_message = """
        <p style="color:#b26a00; font-weight:bold;">
            ⚠️ Your booking was created successfully, but the photo
            could not be uploaded. You can upload it later from
            My Bookings.
        </p>
        """

    else:
        photo_message = ""

    # -----------------------------------------
    # SUCCESS PAGE
    # -----------------------------------------
    return f"""
    <!DOCTYPE html>
    <html>
    <head>
        <title>Booking Confirmed</title>

        <meta name="viewport"
              content="width=device-width, initial-scale=1.0">

        <style>
            body {{
                margin: 0;
                padding: 20px;
                background: #f5f5f5;
                font-family: Arial, sans-serif;
            }}

            .success-box {{
                max-width: 500px;
                margin: 50px auto;
                background: white;
                padding: 30px;
                border-radius: 15px;
                text-align: center;
                box-shadow: 0 4px 15px rgba(0,0,0,0.1);
            }}

            h1 {{
                color: green;
            }}

            .booking-number {{
                font-size: 24px;
                font-weight: bold;
                margin: 20px 0;
            }}

            .btn {{
                display: inline-block;
                margin-top: 20px;
                padding: 12px 20px;
                background: #111;
                color: white;
                text-decoration: none;
                border-radius: 8px;
            }}
        </style>
    </head>

    <body>

        <div class="success-box">

            <h1>✅ Booking Successful!</h1>

            <p>
                Thank you, <strong>{name}</strong>.
            </p>

            <p>
                Your service booking has been created successfully.
            </p>

            <div class="booking-number">
                Booking Reference: #{booking_id}
            </div>

            {photo_message}

            <p>
                Please save your booking reference number.
            </p>

            <a href="/" class="btn">
                Back to Home
            </a>

        </div>

    </body>
    </html>
    """


# =========================================================
# ADMIN LOGIN
# =========================================================

@app.route(
    "/login",
    methods=["GET", "POST"]
)
def login():

    if request.method == "POST":

        username = request.form.get(
            "username",
            ""
        ).strip()

        password = request.form.get(
            "password",
            ""
        )


        # -------------------------------------------------
        # TIME
        # -------------------------------------------------

        current_time = time.time()


        # -------------------------------------------------
        # PREVIOUS ATTEMPTS
        # -------------------------------------------------

        attempts = session.get(
            "login_attempts",
            0
        )

        lock_time = session.get(
            "login_lock_time",
            0
        )


        # -------------------------------------------------
        # CHECK LOCK
        # -------------------------------------------------

        if attempts >= MAX_LOGIN_ATTEMPTS:

            if (
                current_time - lock_time
                < LOCKOUT_TIME
            ):

                remaining = int(
                    LOCKOUT_TIME
                    -
                    (
                        current_time
                        -
                        lock_time
                    )
                )

                return (
                    f"Too many failed attempts. "
                    f"Try again after {remaining} seconds."
                ), 429


            session["login_attempts"] = 0

            session.pop(
                "login_lock_time",
                None
            )

            attempts = 0


        # -------------------------------------------------
        # FIND ADMIN
        # -------------------------------------------------

        connection = get_db_connection()

        try:

            cursor = connection.cursor()

            cursor.execute(
                """
                SELECT id, username, password
                FROM admins
                WHERE username = %s
                """,
                (username,)
            )

            admin = cursor.fetchone()

        finally:

            connection.close()


        # -------------------------------------------------
        # CHECK PASSWORD
        # -------------------------------------------------

        password_correct = False

        if admin:

            password_correct = (
                bcrypt.check_password_hash(
                    admin["password"],
                    password
                )
            )


        # -------------------------------------------------
        # LOGIN SUCCESS
        # -------------------------------------------------

        if password_correct:

            session.clear()

            session.permanent = True

            session["admin_id"] = admin["id"]

            session["username"] = admin["username"]

            return redirect(
                url_for("bookings")
            )


        # -------------------------------------------------
        # LOGIN FAILED
        # -------------------------------------------------

        attempts += 1

        session["login_attempts"] = attempts


        if attempts >= MAX_LOGIN_ATTEMPTS:

            session["login_lock_time"] = current_time

            return (
                "Too many failed attempts. "
                "Login locked for 5 minutes."
            ), 429


        remaining_attempts = (
            MAX_LOGIN_ATTEMPTS
            -
            attempts
        )

        return (
            "Invalid Username or Password. "
            f"{remaining_attempts} attempts remaining."
        ), 401


    return render_template(
        "login.html"
    )


# =========================================================
# LOGOUT
# =========================================================

@app.route("/logout")
@login_required
def logout():

    session.clear()

    return redirect(
        url_for("login")
    )


# =========================================================
# ADMIN BOOKINGS PAGE
# =========================================================

@app.route("/bookings")
@login_required
def bookings():

    connection = get_db_connection()

    try:

        cursor = connection.cursor()


        # -------------------------------------------------
        # ALL BOOKINGS
        # -------------------------------------------------

        cursor.execute(
            """
            SELECT *
            FROM bookings
            ORDER BY id DESC
            """
        )

        bookings = cursor.fetchall()


        # -------------------------------------------------
        # TOTAL
        # -------------------------------------------------

        total_bookings = len(bookings)


        # -------------------------------------------------
        # PENDING
        # -------------------------------------------------

        cursor.execute(
            """
            SELECT COUNT(*)
            FROM bookings
            WHERE status = %s
            """,
            ("Pending",)
        )

        pending_bookings = cursor.fetchone()["count"]


        # -------------------------------------------------
        # IN PROGRESS
        # -------------------------------------------------

        cursor.execute(
            """
            SELECT COUNT(*)
            FROM bookings
            WHERE status = %s
            """,
            ("In Progress",)
        )

        in_progress_bookings = cursor.fetchone()["count"]


        # -------------------------------------------------
        # COMPLETED
        # -------------------------------------------------

        cursor.execute(
            """
            SELECT COUNT(*)
            FROM bookings
            WHERE status = %s
            """,
            ("Completed",)
        )

        completed_bookings = cursor.fetchone()["count"]


        # -------------------------------------------------
        # CANCELLED
        # -------------------------------------------------

        cursor.execute(
            """
            SELECT COUNT(*)
            FROM bookings
            WHERE status = %s
            """,
            ("Cancelled",)
        )

        cancelled_bookings = cursor.fetchone()["count"]

    finally:

        connection.close()


    # -----------------------------------------------------
    # RESPONSE
    # -----------------------------------------------------

    response = make_response(
        render_template(
            "bookings.html",
            bookings=bookings,
            total_bookings=total_bookings,
            pending_bookings=pending_bookings,
            in_progress_bookings=in_progress_bookings,
            completed_bookings=completed_bookings,
            cancelled_bookings=cancelled_bookings
        )
    )


    # Prevent old booking page cache

    response.headers[
        "Cache-Control"
    ] = (
        "no-store, no-cache, "
        "must-revalidate, max-age=0"
    )

    response.headers[
        "Pragma"
    ] = "no-cache"

    response.headers[
        "Expires"
    ] = "0"


    return response


# =========================================================
# UPDATE BOOKING STATUS
# =========================================================

@app.route(
    "/update_status/<int:id>",
    methods=["POST"]
)
@login_required
def update_status(id):

    status = request.form.get(
        "status",
        ""
    ).strip()


    # -----------------------------------------------------
    # ALLOWED STATUS
    # -----------------------------------------------------

    allowed_statuses = [
        "Pending",
        "In Progress",
        "Completed",
        "Cancelled"
    ]


    # -----------------------------------------------------
    # VALIDATE
    # -----------------------------------------------------

    if status not in allowed_statuses:

        return (
            "Invalid booking status.",
            400
        )


    # -----------------------------------------------------
    # UPDATE DATABASE
    # -----------------------------------------------------

    connection = get_db_connection()

    try:

        cursor = connection.cursor()

        cursor.execute(
            """
            UPDATE bookings
            SET status = %s
            WHERE id = %s
            """,
            (
                status,
                id
            )
        )

        connection.commit()

    finally:

        connection.close()


    return redirect(
        url_for("bookings")
    )


# =========================================================
# CUSTOMER VIEW BOOKING DETAILS
# =========================================================

@app.route(
    "/my_booking/<int:id>"
)
def customer_booking_details(id):

    # -----------------------------------------------------
    # CUSTOMER MOBILE SESSION
    # -----------------------------------------------------

    customer_mobile = session.get(
        "customer_mobile"
    )

    # -----------------------------------------------------
    # CUSTOMER NOT VERIFIED
    # -----------------------------------------------------

    if not customer_mobile:

        return redirect(
            url_for("my_bookings")
        )

    # -----------------------------------------------------
    # DATABASE CONNECTION
    # -----------------------------------------------------

    connection = get_db_connection()

    try:

        cursor = connection.cursor()

        # -------------------------------------------------
        # FIND BOOKING
        # -------------------------------------------------

        cursor.execute(
            """
            SELECT *
            FROM bookings
            WHERE id = %s
              AND mobile = %s
            """,
            (
                id,
                customer_mobile
            )
        )

        booking = cursor.fetchone()

        # -------------------------------------------------
        # BOOKING PHOTOS
        # -------------------------------------------------

        cursor.execute(
            """
            SELECT
                id,
                booking_id,
                filename,
                uploaded_at
            FROM booking_photos
            WHERE booking_id = %s
            ORDER BY uploaded_at DESC
            """,
            (id,)
        )

        photos = cursor.fetchall()

    finally:

        connection.close()

    # -----------------------------------------------------
    # BOOKING NOT FOUND
    # -----------------------------------------------------

    if not booking:

        return (
            "Booking not found or access denied.",
            404
        )

    # -----------------------------------------------------
    # SHOW CUSTOMER BOOKING STATUS + PHOTOS
    # -----------------------------------------------------

    return render_template(
        "customer_booking_status.html",
        booking=booking,
        photos=photos
    )

# =========================================================
# ADMIN VIEW BOOKING DETAILS
# =========================================================

@app.route(
    "/booking/<int:id>"
)
@login_required
def view_booking(id):

    connection = get_db_connection()

    try:

        cursor = connection.cursor()

        # -------------------------------------------------
        # FIND BOOKING
        # -------------------------------------------------

        cursor.execute(
            """
            SELECT *
            FROM bookings
            WHERE id = %s
            """,
            (id,)
        )

        booking = cursor.fetchone()

        # -------------------------------------------------
        # BOOKING PHOTOS
        # -------------------------------------------------

        cursor.execute(
            """
            SELECT
                id,
                booking_id,
                filename,
                uploaded_at
            FROM booking_photos
            WHERE booking_id = %s
            ORDER BY uploaded_at DESC
            """,
            (id,)
        )

        photos = cursor.fetchall()

    finally:

        connection.close()

    # -----------------------------------------------------
    # BOOKING NOT FOUND
    # -----------------------------------------------------

    if not booking:

        return (
            "Booking not found.",
            404
        )

    # -----------------------------------------------------
    # ADMIN BOOKING DETAILS
    # -----------------------------------------------------

    return render_template(
        "booking_details.html",
        booking=booking,
        photos=photos
    )


# =========================================================
# DELETE BOOKING
# =========================================================

@app.route(
    "/delete/<int:id>",
    methods=["POST"]
)
@login_required
def delete_booking(id):

    connection = get_db_connection()

    try:

        cursor = connection.cursor()


        # -------------------------------------------------
        # CHECK BOOKING
        # -------------------------------------------------

        cursor.execute(
            """
            SELECT id
            FROM bookings
            WHERE id = %s
            """,
            (id,)
        )

        booking = cursor.fetchone()


        if not booking:

            connection.close()

            return (
                "Booking not found.",
                404
            )


        # -------------------------------------------------
        # DELETE
        # -------------------------------------------------

        cursor.execute(
            """
            DELETE FROM bookings
            WHERE id = %s
            """,
            (id,)
        )

        connection.commit()

    finally:

        connection.close()


    return redirect(
        url_for("bookings")
    )

# =========================================================
# CUSTOMER PHOTO UPLOAD
# =========================================================

@app.route(
    "/my_booking/<int:id>/upload_photo",
    methods=["POST"]
)
def upload_booking_photo(id):

    # -----------------------------------------------------
    # CUSTOMER MOBILE SESSION
    # -----------------------------------------------------

    customer_mobile = session.get(
        "customer_mobile"
    )

    if not customer_mobile:

        return redirect(
            url_for("my_bookings")
        )


    # -----------------------------------------------------
    # CHECK PHOTO
    # -----------------------------------------------------

    photo = request.files.get("photo")

    if not photo or not photo.filename:

        return (
            "Please select an image.",
            400
        )


    # -----------------------------------------------------
    # CHECK FILE TYPE
    # -----------------------------------------------------

    if not allowed_image(photo.filename):

        return (
            "Only JPG, JPEG, PNG and WebP images are allowed.",
            400
        )


    # -----------------------------------------------------
    # VERIFY BOOKING BELONGS TO CUSTOMER
    # -----------------------------------------------------

    connection = get_db_connection()

    try:

        cursor = connection.cursor()

        cursor.execute(
            """
            SELECT id
            FROM bookings
            WHERE id = %s
              AND mobile = %s
            """,
            (
                id,
                customer_mobile
            )
        )

        booking = cursor.fetchone()

    finally:

        connection.close()


    # -----------------------------------------------------
    # ACCESS DENIED
    # -----------------------------------------------------

    if not booking:

        return (
            "Booking not found or access denied.",
            403
        )


    # -----------------------------------------------------
    # UPLOAD TO CLOUDINARY
    # -----------------------------------------------------

    try:

        upload_result = cloudinary.uploader.upload(
            photo,
            folder="golden_car_glass/bookings",
            
        )

    except Exception as e:
        print("CLOUDINARY UPLOAD ERROR:", repr(e))
        return f"Photo upload failed: {e}", 500


    # -----------------------------------------------------
    # CLOUDINARY DETAILS
    # -----------------------------------------------------

    secure_url = upload_result.get(
        "secure_url"
    )

    public_id = upload_result.get(
        "public_id"
    )


    if not secure_url:

        return (
            "Photo upload failed.",
            500
        )


    # -----------------------------------------------------
    # SAVE PHOTO RECORD
    # -----------------------------------------------------

    connection = get_db_connection()

    try:

        cursor = connection.cursor()

        cursor.execute(
            """
            INSERT INTO booking_photos
            (
                booking_id,
                filename
            )
            VALUES (%s, %s)
            """,
            (
                id,
                secure_url
            )
        )

        connection.commit()

    finally:

        connection.close()


    # -----------------------------------------------------
    # SUCCESS
    # -----------------------------------------------------

    return redirect(
        url_for(
            "customer_booking_details",
            id=id
        )
    )

# =========================================================
# CUSTOMER MY BOOKINGS
# =========================================================

@app.route(
    "/my_bookings",
    methods=["GET", "POST"]
)
def my_bookings():

    # -----------------------------------------------------
    # CUSTOMER ENTERS MOBILE NUMBER
    # -----------------------------------------------------

    if request.method == "POST":

        mobile = request.form.get(
            "mobile",
            ""
        ).strip()


        # -------------------------------------------------
        # VALIDATE MOBILE
        # -------------------------------------------------

        if not mobile:

            return render_template(
                "my_bookings.html",
                error="Please enter your mobile number."
            )


        if not mobile.isdigit():

            return render_template(
                "my_bookings.html",
                error="Please enter numbers only."
            )


        if len(mobile) != 10:

            return render_template(
                "my_bookings.html",
                error="Please enter a valid 10-digit mobile number."
            )


        # -------------------------------------------------
        # SAVE CUSTOMER MOBILE IN SESSION
        # -------------------------------------------------

        session["customer_mobile"] = mobile
        session["my_bookings_searched"] = True

        return redirect(
            url_for("my_bookings")
        )


    # -----------------------------------------------------
    # GET MOBILE FROM SESSION
    # -----------------------------------------------------

    mobile = session.get(
        "customer_mobile"
    )

    searched = session.get(
    "my_bookings_searched",
    False
    )

    # -----------------------------------------------------
    # IF MOBILE NOT ENTERED
    # -----------------------------------------------------

    if not mobile:

        return render_template(
            "my_bookings.html"
        )


    # -----------------------------------------------------
    # FIND CUSTOMER BOOKINGS
    # -----------------------------------------------------

    connection = get_db_connection()

    try:

        cursor = connection.cursor()

        cursor.execute(
            """
            SELECT
                id,
                name,
                car_model,
                glass_type,
                date,
                status
            FROM bookings
            WHERE mobile = %s
            ORDER BY id DESC
            """,
            (mobile,)
        )

        bookings = cursor.fetchall()

    finally:

        connection.close()


    # -----------------------------------------------------
    # SHOW BOOKINGS
    # -----------------------------------------------------

    return render_template(
    "my_bookings.html",
    bookings=bookings,
    mobile=mobile,
    searched=searched
    )

    # -----------------------------------------------------
    # CUSTOMER MOBILE SESSION
    # -----------------------------------------------------

    customer_mobile = session.get(
        "customer_mobile"
    )


    # -----------------------------------------------------
    # CUSTOMER NOT VERIFIED
    # -----------------------------------------------------

    if not customer_mobile:

        return redirect(
            url_for("my_bookings")
        )


    # -----------------------------------------------------
    # FIND BOOKING
    # -----------------------------------------------------

    connection = get_db_connection()

    try:

        cursor = connection.cursor()

        cursor.execute(
            """
            SELECT *
            FROM bookings
            WHERE id = %s
              AND mobile = %s
            """,
            (
                id,
                customer_mobile
            )
        )

        booking = cursor.fetchone()

    finally:

        connection.close()


    # -----------------------------------------------------
    # BOOKING NOT FOUND
    # -----------------------------------------------------

    if not booking:

        return (
            "Booking not found or access denied.",
            404
        )


    # -----------------------------------------------------
    # SHOW CUSTOMER BOOKING STATUS
    # -----------------------------------------------------

    return render_template(
        "customer_booking_status.html",
        booking=booking
    )


# =========================================================
# CUSTOMER MY BOOKINGS LOGOUT
# =========================================================

@app.route(
    "/my_bookings/clear"
)
def clear_customer_bookings():

    session.pop(
        "customer_mobile",
        None
    )

    session.pop(
    "my_bookings_searched",
    None
    )

    return redirect(
        url_for("my_bookings")
    )

# =========================================================
# CUSTOMER TRACK BOOKING
# =========================================================

@app.route(
    "/track_booking",
    methods=["GET", "POST"]
)
def track_booking():

    if request.method == "POST":

        booking_id = request.form.get(
            "booking_id",
            ""
        ).strip()


        # -------------------------------------------------
        # VALIDATE NUMBER
        # -------------------------------------------------

        if not booking_id.isdigit():

            return render_template(
                "track_booking.html",
                error=(
                    "Please enter a valid "
                    "Booking Reference Number."
                )
            )


        connection = get_db_connection()

        try:

            cursor = connection.cursor()


            # -------------------------------------------------
            # FIND BOOKING
            # -------------------------------------------------

            cursor.execute(
                """
                SELECT *
                FROM bookings
                WHERE id = %s
                """,
                (int(booking_id),)
            )

            booking = cursor.fetchone()

        finally:

            connection.close()


        # -------------------------------------------------
        # NOT FOUND
        # -------------------------------------------------

        if not booking:

            return render_template(
                "track_booking.html",
                error=(
                    f"Booking #{booking_id} "
                    "was not found. Please check "
                    "your Booking Reference Number."
                )
            )


        # -------------------------------------------------
        # SHOW STATUS
        # -------------------------------------------------

        return render_template(
            "customer_booking_status.html",
            booking=booking
        )


    return render_template(
        "track_booking.html"
    )


# =========================================================
# 404 ERROR
# =========================================================

@app.errorhandler(404)
def page_not_found(error):

    return """
<!DOCTYPE html>
<html>

<head>

    <title>Page Not Found</title>

    <style>

        body {
            font-family: Arial, sans-serif;
            background: #f4f4f4;
            text-align: center;
            padding-top: 100px;
        }

        .error-box {
            background: white;
            width: 450px;
            max-width: 90%;
            margin: auto;
            padding: 35px;
            border-radius: 12px;
            box-shadow: 0 0 15px rgba(0,0,0,0.15);
        }

        .error-icon {
            font-size: 55px;
        }

        h1 {
            color: #c99a00;
        }

        .home-btn {
            display: inline-block;
            background: #222;
            color: white;
            text-decoration: none;
            padding: 10px 20px;
            border-radius: 6px;
            font-weight: bold;
        }

    </style>

</head>

<body>

    <div class="error-box">

        <div class="error-icon">
            🔍
        </div>

        <h1>
            Page Not Found
        </h1>

        <p>
            Sorry, the page you are looking for
            does not exist.
        </p>

        <a href="/" class="home-btn">
            🏠 Back to Home
        </a>

    </div>

</body>

</html>
""", 404


# =========================================================
# 500 ERROR
# =========================================================

@app.errorhandler(500)
def internal_server_error(error):

    return """
<!DOCTYPE html>
<html>

<head>

    <title>Something Went Wrong</title>

    <style>

        body {
            font-family: Arial, sans-serif;
            background: #f4f4f4;
            text-align: center;
            padding-top: 100px;
        }

        .error-box {
            background: white;
            width: 450px;
            max-width: 90%;
            margin: auto;
            padding: 35px;
            border-radius: 12px;
            box-shadow: 0 0 15px rgba(0,0,0,0.15);
        }

        .error-icon {
            font-size: 55px;
        }

        h1 {
            color: #c99a00;
        }

        .home-btn {
            display: inline-block;
            background: #222;
            color: white;
            text-decoration: none;
            padding: 10px 20px;
            border-radius: 6px;
            font-weight: bold;
        }

    </style>

</head>

<body>

    <div class="error-box">

        <div class="error-icon">
            ⚠️
        </div>

        <h1>
            Something Went Wrong
        </h1>

        <p>
            Sorry, something went wrong on our side.
        </p>

        <p>
            Please try again later.
        </p>

        <a href="/" class="home-btn">
            🏠 Back to Home
        </a>

    </div>

</body>

</html>
""", 500


# =========================================================
# RUN APPLICATION
# =========================================================

if __name__ == "__main__":

    app.run(
        host="0.0.0.0",
        port=5000,
        debug=(
            os.environ
            .get(
                "FLASK_DEBUG",
                "False"
            )
            .lower()
            == "true"
        )
    )